backend:
  name: github
  repo: alperencsknz/keros.github.io
  branch: main
  auth_type: pkce
  app_id: Ov23litPNLhWpbYBQzi1

media_folder: "images"
public_folder: "images"

collections:
  - name: "menu"
    label: "Menü Yönetimi"
    files:
      - label: "Yemekler"
        name: "yemekler"
        file: "menu.json"
        fields:
          - label: "Ürünler"
            name: "items"
            widget: "list"
            fields:
              - {label: "Yemek Adı", name: "name", widget: "string"}
              - {label: "Görsel", name: "image", widget: "image", required: false}
              - {label: "Servis Fiyatı", name: "price_servis", widget: "string", required: false}
              - {label: "Ekmek Arası", name: "price_ekmek", widget: "string", required: false}
              - {label: "Tek Fiyat", name: "price_tek", widget: "string", required: false}

      - label: "Çorbalar"
        name: "corbalar"
        file: "corbalar.json"
        fields:
          - label: "Ürünler"
            name: "items"
            widget: "list"
            fields:
              - {label: "Çorba Adı", name: "name", widget: "string"}
              - {label: "Fiyat", name: "price_tek", widget: "string"}

      - label: "İçecekler"
        name: "icecekler"
        file: "icecekler.json"
        fields:
          - label: "Ürünler"
            name: "items"
            widget: "list"
            fields:
              - {label: "İçecek Adı", name: "name", widget: "string"}
              - {label: "Fiyat", name: "price_tek", widget: "string"}