backend:
   name: github
   repo: alperencsknz/keros.github.io
   branch: main
   auth_type: pkce
   app_id: Ov23litPNLhWpbYBQzi1

media_folder: "img"
public_folder: "img"

collections:
  - name: "menu"
    label: "Menü Paneli"
    files:
      - label: "Yemekler Listesi"
        name: "yemekler"
        file: "menu.json"
        fields:
          - label: "Ürünler"
            name: "items"
            widget: "list"
            fields:
              - {label: "Yemek Adı", name: "name", widget: "string"}
              - {label: "Görsel (İsteğe Bağlı)", name: "image", widget: "image", required: false}
              - {label: "Servis Fiyatı", name: "price_servis", widget: "string", required: false}
              - {label: "Ekmek Arası Fiyatı", name: "price_ekmek", widget: "string", required: false}
              - {label: "Tek Fiyat", name: "price_tek", widget: "string", required: false}
